title = "Wrobel dot Dev"
baseurl = "/"
languageCode = "en-us"
theme = "hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Personal website and Blog of Taylor Wrobel"
  keywords = ["personal", "homepage", "blog", "development", "programming", "software"]
  images = [""]
  homeSubtitle = "Adventures in the creation, testing, qualification, and destruction of software"

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

  [[params.social]]
    name = "email"
    url  = "mailto:hi@wrobel.dev"

  [[params.social]]
    name = "github"
    url  = "https://github.com/twrobel3"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/taylorwrobel"

[languages]
  [languages.en]
    title = "Wrobel Dot Dev"
    subtitle = "On the building and breaking software"
    keywords = ""
    copyright = "<a rel=\"license\" href=\"http://creativecommons.org/licenses/by-sa/4.0/\"><img alt=\"Creative Commons License\" style=\"border-width: 0; display: inline;\" src=\"/CC-BY-SA_icon.svg\" /></a>"
    readOtherPosts = "Read more"

    [languages.en.params.logo]
      logoText = "cd ~/wrobel-dot-dev"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "privacy"
    name       = "Privacy"
    url        = "/privacy"
